### ISSUE TITLE
Installation of further Plugins fails

### ISSUE THREAD

**Issue by planctron** [aheimsbakk/container-etherpad#1]
It's a nice idea - if it works correctly.
I lost an hour of research to find out that **only** with the  original   etherpad/etherpad  image we can install additional plugins via  admin url.
Here with this image, it fails!
And it fails in a very inconvenient way without error message!
Container logs show that the plugin was installed. But nothing is loaded afterwards.
Test:  Start with a docker compose file, setting an admin PW like:

```
version: "3"
services:
  etherpad:
    image: aheimsbakk/etherpad:latest    #(replace with  etherpad/etherpad:latest
    container_name: etherpad
    ports:
      - "9881:9001"
    volumes:
      - etherpad-data:/opt/etherpad-lite/var
     #      - ./config/settings.json:/opt/etherpad-lite/settings.json
    environment:
      - ADMIN_PASSWORD=<secret>
volumes:
  etherpad-data:
    driver: local
```

Here I linked the  settings file (only).  It is required since the admin change of the settings does not work
probably due to Port mappings.

Configure reverse proxy   pointing to  9881 ...

Try to install plugins via   https://.../admin     NOT WORKING!

Then just replace the  image to "etherpad/etherpad".
